#!/bin/bash

msg "Checking ${RUN_DIR}"

volume_setup() {
    local run_fs=$(df --output=source ${RUN_DIR} | sed -n 2p)

    [ "${run_fs}" != "none" ] || error "No volume mounted on ${RUN_DIR}" 254

    if [ -f "${RUN_DIR}/.volume_setup" ]; then
        msg "${RUN_DIR} appears to be setup!"
        return
    fi

    (
        cd ${RUN_DIR}/conf
        sed -n '/^[A-Za-z]/s/[ ]*=.*//p' config.lua | while read var
        do
            env_var=${var^^}

            if [ -n "${!$env_var}" ]; then
                echo "** Setting ${var} = ${!env_var}"
                sed -e 's/^\('"${var}"'[ ]*=[ ]*["]*\)[^" \t]*\(.*\)/\1'"${!env_var}"'\2/' -i config.lua
            fi
        done
        date > ${RUN_DIR}/.volume_setup
    )
}

volume_setup
