#!/bin/bash
#
# 20updates - update packages
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Mon Dec 28 16:42:16 EST 2015
#

(
    # die on error
    set -e

    export DEBIAN_FRONTEND=noninteractive

    # Get latest repo locations
    apt-get update

    # Upgrade whatever we can
    for i in 1 2 3
    do
        if apt-get -y -o Dpkg::Options::="--force-confnew" dist-upgrade; then
            break
        else
            notice "apt-get dist-upgrade failed RET=$? RETRY=$i"
        fi
    done

    msg "Install Run Packages"

    echo ">> RUN_PACKAGES: $RUN_PACKAGES"

    for i in 1 2 3
    do
        if apt-get -y install $PACKAGES $EXTRA_PACKAGES; then
            break
        else
            notice "apt-get failed RET=$? RETRY=$i"
        fi
    done

    # Save list of what is manually installed
    apt-mark showmanual > ${ZDHOME}/run_packages.txt
)

ret=$?
if [ ${ret} -ne 0 ]; then
    msg "ERROR: ${ME} returned ${ret}"
    exit ${ret}
fi
