#!/bin/bash
#
# 32emuyoda - Install and Setup EmuYoda
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Sun Jan 24 20:29:52 EST 2016
#

install_yoda() {
    if [ -d "${EMUYODA_DIR}/." ]; then
	return 1
    fi

    echo "** setting up emuyoda **"
    (
	ln -vs ${ZDHOME}/ZonamaContainer/server/emuyoda ${EMUYODA_DIR}

	cp -v ${ZDHOME}/ZonamaContainer/server/openresty/nginx/conf/* ${OPENRESTY_DIR}/nginx/conf

	sed -e "/^yodaSecret.*/s//yodaSecret = '$(dd if=/dev/urandom bs=1024 count=1 2> /dev/null|md5sum|cut -d' ' -f1)'/" -e "/^server_ip/d" ${EMUYODA_DIR}/yoda-config.lua.in > ${EMUYODA_DIR}/yoda-config.lua

	notice "EmuYoda Installed" "The EmuYoda API and Web Interface has been installed."
    )

    return 0
}

install_yoda
