#!/bin/bash
#
# 32emuyoda - Install and Setup EmuYoda
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Sun Jan 24 20:29:52 EST 2016
#

install_yoda() {
    if [ -d "${EMUYODA_DIR}/." ]; then
	return 1
    fi

    echo "** setting up emuyoda **"
    (
	ln -vs ${ZDHOME}/ZonamaContainer/server/emuyoda ${EMUYODA_DIR}

	cp -v ${ZDHOME}/ZonamaContainer/server/openresty/nginx/conf/* ${OPENRESTY_DIR}/nginx/conf

	sed -e "/^yodaSecret.*/s//yodaSecret = '$(LC_CTYPE=C < /dev/urandom tr -dc "A-Za-z0-9" | head -c32)'/" > ${EMUYODA_DIR}/yoda-config.lua

	notice "EmuYoda Installed" "The EmuYoda API and Web Interface has been installed."
    )

    return 0
}

install_yoda
