#!/bin/bash
#
# 55clone - Clone the git repos
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Fri Jan  8 07:19:47 EST 2016
#
# Depends: REPO_PUBLIC_URL REPO WORKSPACE
#

for depend in WORKSPACE CORE3_REPO_URL CORE3_BRANCH ENGINE_REPO_URL ENGINE_BRANCH
do
    if [ -n "${!depnd}" ]; then
        error "Required setting ${depend} missing." 155
    fi
done

clone_repos() {
    msg "Cloning Core3: ${CORE3_REPO_URL} (${CORE3_BRANCH})"
    git clone --progress -b ${CORE3_BRANCH} ${CORE3_REPO_URL} "${WORKSPACE}/Core3" &
    msg "Cloning Engine: ${ENGINE_REPO_URL} (${ENGINE_BRANCH})"
    git clone --progress -b ${ENGINE_BRANCH} ${ENGINE_REPO_URL} "${WORKSPACE}/PublicEngine" &
    wait
}

make_links() {
    ( set -x
	rm -f MMOCoreORB MMOEngine Core3/MMOEngine
	[ -d Core3 ] && (cd $PWD/Core3;ln -s ../PublicEngine/MMOEngine .)
	[ -d PublicEngine ] && ln -s PublicEngine/MMOEngine .
	[ -d Core3 ] && ln -s Core3/MMOCoreORB .
	if [ -f PublicEngine/MMOEngine/bin/idlc -a ! -x /usr/local/bin/idlc ]; then
	    (echo export CLASSPATH=$PWD/PublicEngine/MMOEngine/bin/idlc.jar;cat PublicEngine/MMOEngine/bin/idlc) > /usr/local/bin/idlc
	    sudo chmod 755 /usr/local/bin/idlc
	fi
    )

    local englib=PublicEngine/MMOEngine/lib/unix/libengine3.a

    if [ ! -L $englib ]; then
	echo "Setup unix library link"
	mkdir -p PublicEngine/MMOEngine/lib/unix > /dev/null 2>&1
	(
	    cd PublicEngine/MMOEngine/lib/unix
	    if [ $(uname -s) = "Darwin" ]; then
		ln -s ../lion64/libengine3.a
	    else
	    case $(uname -m) in
		x86_64 ) ln -s ../linux64/libengine3.a ;;
		i386 ) ln -s ../linux32/libengine3.a ;;
	    esac
	    fi
	)
    fi

    echo "Using engine library: $(readlink $englib)"
}

[ ! -d $WORKSPACE ] && mkdir $WORKSPACE && echo "Created $WORKSPACE"
pushd $WORKSPACE
clone_repos
make_links
popd
