#!/bin/bash
#
# 95sysprep - finalize build (called from Docker build)
#
# Author: Lord Kator <lordkator@swgemu.com>
#
# Created: Sat Sep 23 08:38:51 EDT 2017
#

export PATH=${ZDHOME}/ZonamaContainer/container/bin:$PATH

cd ${ZDHOME}

version=${ZC_VERSION:-"0.0.0"}
builder_name="${ZC_BUILDER:-docker}"
build_timestamp=$(date +%s)
build_datetime=$(date -u --date="@${build_timestamp}" "+%Y-%m-%dT%H:%M:%SZ")

###################################################
## Clean up any misc stuff in dev's user account ##
###################################################
echo ">> Cleanup files that shouldn't be in the image."
(
    cd ${ZDHOME}
    rm -rf .bash* .profile .inputrc .vim* .cache /var/mail/* .ssh/config .visual .gerrit_username .mysql_history .devsetup.ran .tzdata.ran .config/ZonamaContainer/config
    rm -rf .xsession* .gitconfig .lesshst .ssh/id_* .subversion .cache .force_ip .iplist* .ssh/authorized_keys
) 2> /dev/null

# Basic files
cp -vr /etc/skel/. ${ZDHOME}

##########################
## Cleanup all the logs ##
##########################
echo ">> Cleanup /var/log"
find /var/log -name \*.gz -o -name \*.[0-9] | xargs --no-run-if-empty -t rm 

rm -fr /var/tmp/* /tmp/* /etc/ssh/ssh_host*_key* /root/.viminfo /root/.bash_history /root/.lesshst /root/.bash_history /root/.ssh/* /var/log/*.gz /var/log/*.[1-9]* /var/log/*.old /var/spool/anacron/* /var/spool/mail/* /var/lib/dpkg/lock /var/cache/apt/archives/lock

find /var/log ${ZDHOME}/server/openresty/nginx/logs -type f | while read fn
do
    cp /dev/null "$fn"
done

#################################
## Save version and build info ##
#################################
echo "$version" > /.swgemudev.version
chmod 644 /.swgemudev.version
echo '{ "build_version": "'"${version}"'", "build_timestamp": '"${build_timestamp}"', "build_datetime": "'"${build_datetime}"'", "builder_name": "'"${builder_name}"'" }' | tee /.swgemudev.buildinfo.json | python -m json.tool

#####################
## Fix permissions ##
#####################
chown -R ${ZDUSER}:${ZDUSER} ${ZDHOME}
