#!/bin/bash

cat << EOF > /etc/supervisor/conf.d/supervisord-core3.conf
[supervisord]
nodaemon=true

[program:nginx]
user=swgemu
command=${ZDHOME}/server/openresty/nginx/sbin/nginx
directory=/home/swgemu

[program:server]
user=swgemu
directory=/home/swgemu
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
command=${ZDHOME}/ZonamaContainer/container/scripts/start-server
EOF
