#!/bin/bash

cat << EOF > /etc/supervisor/conf.d/supervisord-core3.conf
[supervisord]
nodaemon=true

[program:nginx]
user=swgemu
command=${ZDHOME}/server/openresty/nginx/sbin/nginx -g "daemon off;"
directory=/home/swgemu

[program:server]
user=swgemu
directory=/home/swgemu
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
startretries=1000
command=${ZDHOME}/ZonamaContainer/container/scripts/start-server
EOF
