#!/bin/bash
#
# 98stage - Cleanup and stage binaries for container load
#

stage() {
    msg "Stage run_dir for container start"
    mkdir -p ${RUN_DIR}
    (
        set -xe
        cd ${WORKSPACE}/Core3/MMOCoreORB/bin
        read bytes _<<<$(du -sb .)
        echo $bytes > ${RUN_DIR}-size
        tar cf - . | pv | gzip > ${RUN_DIR}-stage.tar.gz
    )

    local ret=$?

    [ "$ret" -eq 0 ] || error "Staging failed! RET=$?"

    msg "Cleanup packages"
    apt-mark showmanual | xargs -t apt-mark auto

    cat ${ZDHOME}/run_packages.txt | xargs -t apt-mark manual

    apt-get purge -y --auto-remove

    msg "Remove build files and packages"
    rm -fr ${WORKSPACE} /var/lib/apt/lists/* /usr/share/man/man* /usr/local/bin/idlc
}

stage
